# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Football Leagues' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

pod 'RxSwift'
pod 'RxCocoa'
pod 'Swinject'
pod 'SwinjectStoryboard'
pod 'Moya/RxSwift'
  target 'Football LeaguesTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'Football LeaguesUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
